### ISSUE TITLE
Possibility of adding a simple callback as the second param of `transform`

### ISSUE THREAD

**Issue by arthurfiorette** [mcollina/syncthrough#16]
In some of my usecases, the transformation steps results into `T` or `Promise<T>`, Promises shouldn't be handled by this library, but if transform could use a `callback`, this would be resolved as following:

```ts
syncthrough((data, cb) => {
  const result = myFn(data)
  
  if (result instanceof Promise) {
    result.then(r => cb(null, r), e => cb(e, null))
  } else {
    return result
  }
})
```

which could simply translate to moving this code into a function:

https://github.com/mcollina/syncthrough/blob/b39fcf932b0545f8b6e7b2df31b6cf59943f509b/syncthrough.js#L112-L129

and modifying the `_transform` call to the below:

```ts
const res = this._transform(chunk, emit)

if(res !== undefined) {
  emit(res)
}

function emit() { ... }
```

Of course the above is just a example and probably a way to handle callback errors should be done. I'm also happy to do a PR, just would love some guidance on handling errors passed to the callback.

**Comment by mcollina** [comment]
The goal of the module is to provide synchronous mapping, and fast processing in case of a 1-1 mapping. I’m planning to work on some utilities for promises in https://github.com/mcollina/fastp. subscribe to that repo, will publish something soon.
