### ISSUE TITLE
Readme: use `pipeline`?

### ISSUE THREAD

**Issue by BMorearty** [mcollina/syncthrough#19]
I learned about this package from your post, [3x Faster Stream processing](https://adventures.nodeland.dev/archive/3x-faster-stream-processing/). In that post you used `pipeline`, which is different from the code sample in the readme which uses `pipe`.

I’m not sure if it’s important to use one vs. the other but I’m assuming `pipeline` might be the more modern way to do it so maybe the readme should be updated?

Code from the readme:

```js
'use strict'

var fs = require('fs')
var syncthrough = require('syncthrough')

fs.createReadStream(__filename)
  .pipe(syncthrough(function (chunk) {
	// there is no callback here
	// you can return null to end the stream
	// returning undefined will let you skip this chunk
	return chunk.toString().toUpperCase()
  }))
  .pipe(process.stdout, { end: false })
```

Code from the blog post:

```js
import { createReadStream } from 'node:fs'
import { pipeline } from 'node:stream/promises'
import { syncthrough } from 'syncthrough'

await pipeline(
  createReadStream(import.meta.filename),
  syncthrough(function (chunk) {
    // there is no callback here
    // you can return null to end the stream
    // returning undefined will let you skip this chunk
    return chunk.toString().toUpperCase()
  }),
  process.stdout)
```

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue?

**Comment by BMorearty** [comment]
Sure. 👍🏻
