### ISSUE TITLE
clarification: why does it not work with streams1?

### ISSUE THREAD

**Issue by dominictarr** [mcollina/syncthrough#3]
just curious, seems to me this should be able to work with streams1? what is the reason that it does not work?

**Comment by mcollina** [comment]
Good Q. The problem with streams1 API is that the `write()` result is extremely often miscarded, and `pause()` is advisory only, as in https://github.com/nodejs/node/blob/master/lib/stream.js#L32.

If `pause()` does its job of pausing the stream, then yes, it's _should_ be compatibile with streams1, but I have not tested. A lot of implementations do not properly implement `pause()`.

It would be fantastic to port some of this logic into `Transform`, but I have yet to identify a way to do so.

**Comment by dominictarr** [comment]
`though` (which you mention in the readme) does handle pause correctly, so anything based on that (if used correctly) should be compatible.
