### ISSUE TITLE
syncthrough diff Transform stream and through2

### ISSUE THREAD

**Issue by zhangwinning** [mcollina/syncthrough#7]
Hi @mcollina 
I saw the syncthrough and transform code, find it logic is similar. I don't know the diff is ?  you can write is below it 

> syncthrough enforces backpressure, but it maintain no internal buffering, allowing much greater throughput. In fact, it delivers 10x performance over a standard Transform.

However I see transform logic not internal buffering yet.  so what is casing the delivers 10x performance over a standard Transform?  Is't transform don't backpressure

Looking forward to your reply

**Comment by mcollina** [comment]
Exactly that! This library does not buffer, while Transform buffers twice (once on the Readable side and once on Writable side).
